Update close-xr30.yml

diff --git a/.github/workflows/close-xr30.yml b/.github/workflows/close-xr30.yml
--- a/.github/workflows/close-xr30.yml
+++ b/.github/workflows/close-xr30.yml
@@ -217,16 +217,28 @@ jobs:
       run: |
         cd openwrt
         echo -e "$(nproc) thread compile"
-        make -j$(nproc) || make -j1 || make -j1 V=s
+        
+        # 尝试使用多线程编译
+        echo "Attempting to compile with $(nproc) threads: make -j$(nproc)"
+        make -j$(nproc) || (
+          # 如果多线程编译失败，尝试单线程编译
+          echo "Multi-threaded compilation failed, attempting single-threaded compilation: make -j1"
+          make -j1 || (
+            # 如果单线程编译失败，尝试 verbose 模式单线程编译
+            echo "Single-threaded compilation failed, attempting verbose single-threaded compilation: make -j1 V=s"
+            make -j1 V=s
+          )
+        )
+        
         echo "::set-output name=status::success"
-
+    
         sed -nE 's/.*(192.168\.[0-9]+\.[0-9]+).*/\1/p' package/base-files/files/bin/config_generate | head -n 1 > IP_ADDR
         [ -s IP_ADDR ] && echo "IP_ADDR=$(cat IP_ADDR)" >> $GITHUB_ENV
-
+    
         grep '^CONFIG_TARGET_DEVICE.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
         [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
         echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
-
+    
         if grep -q 'CONFIG_PACKAGE_mtwifi-cfg=y' .config; then
             echo "WIFI_INTERFACE=-mtwifi" >> $GITHUB_ENV
         else
@@ -239,7 +251,7 @@ jobs:
         fi
         echo "FILE_DATE=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV
         echo "status=success" >> $GITHUB_OUTPUT
-
+    
     - name: 检查github储存空间情况  Check space usage
       if: (!cancelled())
       run: df -hT
