Update close-xr30.yml

diff --git a/.github/workflows/close-xr30.yml b/.github/workflows/close-xr30.yml
--- a/.github/workflows/close-xr30.yml
+++ b/.github/workflows/close-xr30.yml
@@ -249,7 +249,16 @@ jobs:
       run: |
         ls -lah openwrt/dl || echo "dl 不存在"
         ls -lah openwrt/build_dir || echo "build_dir 不存在"  
-
+    - name: 打印.config
+      id: print
+      run: |
+        cat .config
+        
+    - name: 打印feeds.conf.default
+      id: printfeed
+      run: |
+        cat feeds.conf.default
+        
     - name: 下载安装包
       id: package
       run: |
@@ -259,34 +268,38 @@ jobs:
         find dl -size -1024c -exec ls -l {} \;
         find dl -size -1024c -exec rm -f {} \;
 
-    - name: 编译固件
+    - name: 开始编译固件  Compile the firmware
       id: compile
       run: |
         cd openwrt
         echo -e "$(nproc) thread compile"
-        make -j$(nproc) || make -j1 || make -j1 V=s
         
-        sed -n 's/.*lan) ipad=${ipaddr:-"\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)"} ;;.*/\1/p' package/base-files/files/bin/config_generate | head -n 1 > IP_ADDR
+        # 尝试使用多线程编译
+        echo "Attempting to compile with $(nproc) threads: make -j$(nproc)"
+        make -j$(nproc) || (
+          # 如果多线程编译失败，尝试 verbose 模式单线程编译
+          echo "Multi-threaded compilation failed, attempting single-threaded compilation: make -j1"
+          make -j1 V=s
+          )
+        
+        echo "status=success" >> $GITHUB_OUTPUT
+    
+        sed -nE 's/.*(192.168\.[0-9]+\.[0-9]+).*/\1/p' package/base-files/files/bin/config_generate | head -n 1 > IP_ADDR
         [ -s IP_ADDR ] && echo "IP_ADDR=$(cat IP_ADDR)" >> $GITHUB_ENV
-        if grep -q 'CONFIG_MTK_MT_WIFI_DRIVER_VERSION_7661=y' .config; then
-                echo "WIFI_VERSION=-v7661" >> $GITHUB_ENV
-        else
-                echo "WIFI_VERSION=-v7672" >> $GITHUB_ENV
-        fi
-        if [ ${{ github.event.inputs.EEPROM }} == 'true' ]; then
-                echo "EEPROM=-eeprom" >> $GITHUB_ENV
-        else
-                echo "EEPROM=" >> $GITHUB_ENV
-        fi
+    
+        grep '^CONFIG_TARGET_DEVICE.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
+        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
+        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
+    
         if grep -q 'CONFIG_PACKAGE_mtwifi-cfg=y' .config; then
-                echo "WIFI_INTERFACE=-mtwifi" >> $GITHUB_ENV
+            echo "WIFI_INTERFACE=-mtwifi" >> $GITHUB_ENV
         else
-                echo "WIFI_INTERFACE=" >> $GITHUB_ENV
+            echo "WIFI_INTERFACE=" >> $GITHUB_ENV
         fi
         if grep -q 'CONFIG_PACKAGE_luci-app-dockerman=y' .config; then
-                echo "BUILD_DOCKERMAN=-docker" >> $GITHUB_ENV
+            echo "BUILD_DOCKERMAN=-docker" >> $GITHUB_ENV
         else
-                echo "BUILD_DOCKERMAN=" >> $GITHUB_ENV
+            echo "BUILD_DOCKERMAN=" >> $GITHUB_ENV
         fi
         echo "FILE_DATE=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV
         echo "status=success" >> $GITHUB_OUTPUT
